[package]
name = "inspect-asm"
version = "0.1.0"
edition = "2021"

[dependencies]
allocator-api2 = "0.2.21"
blink-alloc = "0.3.1"
bump-scope = "1.2.0"
bumpalo = { version = "3.19.0", features = ["allocator-api2"] }
